//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoRIOControl.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ProtoRIOControl.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        public static string PneumaticsTab {
            get {
                return ResourceManager.GetString("PneumaticsTab", resourceCulture);
            }
        }
        
        public static string PWMTab {
            get {
                return ResourceManager.GetString("PWMTab", resourceCulture);
            }
        }
        
        public static string SensorsTab {
            get {
                return ResourceManager.GetString("SensorsTab", resourceCulture);
            }
        }
        
        public static string StatusNotConnected {
            get {
                return ResourceManager.GetString("StatusNotConnected", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string StatusTab {
            get {
                return ResourceManager.GetString("StatusTab", resourceCulture);
            }
        }
        
        public static string EnableBTTitle {
            get {
                return ResourceManager.GetString("EnableBTTitle", resourceCulture);
            }
        }
        
        public static string EnableBTMessage {
            get {
                return ResourceManager.GetString("EnableBTMessage", resourceCulture);
            }
        }
        
        public static string EnableBTConfirm {
            get {
                return ResourceManager.GetString("EnableBTConfirm", resourceCulture);
            }
        }
        
        public static string EnableBTCancel {
            get {
                return ResourceManager.GetString("EnableBTCancel", resourceCulture);
            }
        }
        
        public static string BatteryVoltage {
            get {
                return ResourceManager.GetString("BatteryVoltage", resourceCulture);
            }
        }
        
        public static string BatteryCurrent {
            get {
                return ResourceManager.GetString("BatteryCurrent", resourceCulture);
            }
        }
        
        public static string PWMA {
            get {
                return ResourceManager.GetString("PWMA", resourceCulture);
            }
        }
        
        public static string PWMB {
            get {
                return ResourceManager.GetString("PWMB", resourceCulture);
            }
        }
        
        public static string NegFull {
            get {
                return ResourceManager.GetString("NegFull", resourceCulture);
            }
        }
        
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        public static string SolenoidA {
            get {
                return ResourceManager.GetString("SolenoidA", resourceCulture);
            }
        }
        
        public static string SolenoidB {
            get {
                return ResourceManager.GetString("SolenoidB", resourceCulture);
            }
        }
        
        public static string AllowBothSolenoid {
            get {
                return ResourceManager.GetString("AllowBothSolenoid", resourceCulture);
            }
        }
        
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        public static string SelectSensor {
            get {
                return ResourceManager.GetString("SelectSensor", resourceCulture);
            }
        }
        
        public static string SensorA {
            get {
                return ResourceManager.GetString("SensorA", resourceCulture);
            }
        }
        
        public static string SensorB {
            get {
                return ResourceManager.GetString("SensorB", resourceCulture);
            }
        }
        
        public static string AlertBtErrorMessage {
            get {
                return ResourceManager.GetString("AlertBtErrorMessage", resourceCulture);
            }
        }
        
        public static string AlertBtErrorTitle {
            get {
                return ResourceManager.GetString("AlertBtErrorTitle", resourceCulture);
            }
        }
        
        public static string AlertInvalidDeviceMessage {
            get {
                return ResourceManager.GetString("AlertInvalidDeviceMessage", resourceCulture);
            }
        }
        
        public static string AlertInvalidDeviceTitle {
            get {
                return ResourceManager.GetString("AlertInvalidDeviceTitle", resourceCulture);
            }
        }
        
        public static string AlertLostConnectionMessage {
            get {
                return ResourceManager.GetString("AlertLostConnectionMessage", resourceCulture);
            }
        }
        
        public static string AlertLostConnectionTitle {
            get {
                return ResourceManager.GetString("AlertLostConnectionTitle", resourceCulture);
            }
        }
        
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        public static string TapToConnect {
            get {
                return ResourceManager.GetString("TapToConnect", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string UnknownDevice {
            get {
                return ResourceManager.GetString("UnknownDevice", resourceCulture);
            }
        }
        
        public static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        public static string AlertConnectFailTitle {
            get {
                return ResourceManager.GetString("AlertConnectFailTitle", resourceCulture);
            }
        }
        
        public static string AlertConnectFailMessage {
            get {
                return ResourceManager.GetString("AlertConnectFailMessage", resourceCulture);
            }
        }
        
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        public static string ConfirmDisconnectTitle {
            get {
                return ResourceManager.GetString("ConfirmDisconnectTitle", resourceCulture);
            }
        }
        
        public static string ConfirmDisconnectMessage {
            get {
                return ResourceManager.GetString("ConfirmDisconnectMessage", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
    }
}
