//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoRIOControl.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoRIOControl.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Low Energy (4.0) is not supported on this device..
        /// </summary>
        public static string AlertBtErrorMessage {
            get {
                return ResourceManager.GetString("AlertBtErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Error.
        /// </summary>
        public static string AlertBtErrorTitle {
            get {
                return ResourceManager.GetString("AlertBtErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to .
        /// </summary>
        public static string AlertConnectFailMessage {
            get {
                return ResourceManager.GetString("AlertConnectFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Failed.
        /// </summary>
        public static string AlertConnectFailTitle {
            get {
                return ResourceManager.GetString("AlertConnectFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connected device does not appear to be a ProtoRIO. Communication could not be established..
        /// </summary>
        public static string AlertInvalidDeviceMessage {
            get {
                return ResourceManager.GetString("AlertInvalidDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Device.
        /// </summary>
        public static string AlertInvalidDeviceTitle {
            get {
                return ResourceManager.GetString("AlertInvalidDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the bluetooth device was lost..
        /// </summary>
        public static string AlertLostConnectionMessage {
            get {
                return ResourceManager.GetString("AlertLostConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Connection.
        /// </summary>
        public static string AlertLostConnectionTitle {
            get {
                return ResourceManager.GetString("AlertLostConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow both on at the same time.
        /// </summary>
        public static string AllowBothSolenoid {
            get {
                return ResourceManager.GetString("AllowBothSolenoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string AmpsSymbol {
            get {
                return ResourceManager.GetString("AmpsSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProtoRIO Control.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Current.
        /// </summary>
        public static string BatteryCurrent {
            get {
                return ResourceManager.GetString("BatteryCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Voltage.
        /// </summary>
        public static string BatteryVoltage {
            get {
                return ResourceManager.GetString("BatteryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Setting.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from %DEV%?.
        /// </summary>
        public static string ConfirmDisconnectMessage {
            get {
                return ResourceManager.GetString("ConfirmDisconnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect?.
        /// </summary>
        public static string ConfirmDisconnectTitle {
            get {
                return ResourceManager.GetString("ConfirmDisconnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to .
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EnableBTCancel {
            get {
                return ResourceManager.GetString("EnableBTCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string EnableBTConfirm {
            get {
                return ResourceManager.GetString("EnableBTConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable bluetooth in Settings..
        /// </summary>
        public static string EnableBTMessage {
            get {
                return ResourceManager.GetString("EnableBTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Required.
        /// </summary>
        public static string EnableBTTitle {
            get {
                return ResourceManager.GetString("EnableBTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string ModePercent {
            get {
                return ResourceManager.GetString("ModePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo.
        /// </summary>
        public static string ModeServo {
            get {
                return ResourceManager.GetString("ModeServo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -100%.
        /// </summary>
        public static string NegFull {
            get {
                return ResourceManager.GetString("NegFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pneumatics.
        /// </summary>
        public static string PneumaticsTab {
            get {
                return ResourceManager.GetString("PneumaticsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM A.
        /// </summary>
        public static string PWMA {
            get {
                return ResourceManager.GetString("PWMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM B.
        /// </summary>
        public static string PWMB {
            get {
                return ResourceManager.GetString("PWMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM.
        /// </summary>
        public static string PWMTab {
            get {
                return ResourceManager.GetString("PWMTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sensor.
        /// </summary>
        public static string SelectSensor {
            get {
                return ResourceManager.GetString("SelectSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor A.
        /// </summary>
        public static string SensorA {
            get {
                return ResourceManager.GetString("SensorA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor B.
        /// </summary>
        public static string SensorB {
            get {
                return ResourceManager.GetString("SensorB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorsTab {
            get {
                return ResourceManager.GetString("SensorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180°.
        /// </summary>
        public static string ServoFull {
            get {
                return ResourceManager.GetString("ServoFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0°.
        /// </summary>
        public static string ServoNeg {
            get {
                return ResourceManager.GetString("ServoNeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90°.
        /// </summary>
        public static string ServoNeutral {
            get {
                return ResourceManager.GetString("ServoNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid A.
        /// </summary>
        public static string SolenoidA {
            get {
                return ResourceManager.GetString("SolenoidA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid B.
        /// </summary>
        public static string SolenoidB {
            get {
                return ResourceManager.GetString("SolenoidB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to .
        /// </summary>
        public static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string StatusNotConnected {
            get {
                return ResourceManager.GetString("StatusNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusTab {
            get {
                return ResourceManager.GetString("StatusTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a device to connect to.
        /// </summary>
        public static string TapToConnect {
            get {
                return ResourceManager.GetString("TapToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownDevice {
            get {
                return ResourceManager.GetString("UnknownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string VoltsSymbol {
            get {
                return ResourceManager.GetString("VoltsSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
