//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoRIOControl.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ProtoRIOControl.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        public static string PneumaticsTab {
            get {
                return ResourceManager.GetString("PneumaticsTab", resourceCulture);
            }
        }
        
        public static string PWMTab {
            get {
                return ResourceManager.GetString("PWMTab", resourceCulture);
            }
        }
        
        public static string SensorsTab {
            get {
                return ResourceManager.GetString("SensorsTab", resourceCulture);
            }
        }
        
        public static string StatusNotConnected {
            get {
                return ResourceManager.GetString("StatusNotConnected", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string StatusTab {
            get {
                return ResourceManager.GetString("StatusTab", resourceCulture);
            }
        }
        
        public static string EnableBTTitle {
            get {
                return ResourceManager.GetString("EnableBTTitle", resourceCulture);
            }
        }
        
        public static string EnableBTMessage {
            get {
                return ResourceManager.GetString("EnableBTMessage", resourceCulture);
            }
        }
        
        public static string EnableBTConfirm {
            get {
                return ResourceManager.GetString("EnableBTConfirm", resourceCulture);
            }
        }
        
        public static string EnableBTCancel {
            get {
                return ResourceManager.GetString("EnableBTCancel", resourceCulture);
            }
        }
    }
}
